webimage_extra_packages:
    [chromium, fonts-liberation, libnss3, libgtk-3-0, libasound2, xdg-utils]

web_environment:
    - CPPFLAGS=-DPNG_ARM_NEON_OPT=0
    - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
